version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - ft_transcendance
    env_file: .env
    volumes:
      - ./frontend/:/var/www/frontend/
      - ./backend/staticfiles/:/var/www/backend/staticfiles/

  bck_django:
    container_name: bck_django
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: on-failure
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - ft_transcendance
    volumes:
      - ./backend/:/usr/backend/
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - ft_transcendance
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
    ft_transcendance:
        driver: bridge

volumes:
  postgres_data: