# Generated by Django 5.0.3 on 2024-03-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
        ('tournaments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='player_1',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_1', to='players_manager.player'),
        ),
    ]
