# Generated by Django 5.0.3 on 2024-03-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
        ('tournaments_manager', '0004_alter_tournament_player_1_alter_tournament_player_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='Tournament', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_5', to='players_manager.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_6', to='players_manager.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_7', to='players_manager.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_8', to='players_manager.player'),
        ),
    ]
