# Generated by Django 5.0.3 on 2024-03-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_player_1', to='players_manager.player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_player_2', to='players_manager.player')),
            ],
        ),
    ]
