# Generated by Django 5.0.3 on 2024-03-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_manager', '0001_initial'),
        ('players_manager', '0004_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='players_manager.player'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='players_manager.player'),
        ),
    ]
