# Generated by Django 5.0.3 on 2024-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_manager', '0002_alter_friend_player_1_alter_friend_player_2'),
        ('players_manager', '0004_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_manager.player'),
        ),
    ]
