# Generated by Django 5.0.3 on 2024-03-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Four_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('score_player3', models.IntegerField(default=0)),
                ('score_player4', models.IntegerField(default=0)),
                ('score_max', models.IntegerField(default=5)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Four_player_1', to='players_manager.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Four_player_2', to='players_manager.player')),
                ('player3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Four_player_3', to='players_manager.player')),
                ('player4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Four_player_4', to='players_manager.player')),
                ('win_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_player_four', to='players_manager.player')),
            ],
        ),
    ]
