# Generated by Django 5.0.4 on 2024-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_2p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_2p_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_2p_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_4p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_4p_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_4p_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('PLAYING', 'Playing')], default='OFFLINE', max_length=200),
        ),
    ]
