# Generated by Django 5.0.4 on 2024-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
