# Generated by Django 5.0.4 on 2024-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0004_alter_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.png', max_length=200, upload_to='avatars/'),
        ),
    ]
