# Generated by Django 5.0.3 on 2024-03-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0005_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nb_games_2p_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
