# Generated by Django 5.0.4 on 2024-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0006_alter_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='avatar.png', max_length=200, upload_to='avatars/'),
        ),
    ]
