# Generated by Django 5.0.3 on 2024-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0007_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
