# Generated by Django 5.0.4 on 2024-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0008_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nb_points_4p',
            field=models.IntegerField(default=0),
        ),
    ]
