# Generated by Django 5.0.3 on 2024-03-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0008_player_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
    ]
