# Generated by Django 5.0.3 on 2024-03-28 11:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0009_alter_player_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
