# Generated by Django 5.0.4 on 2024-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0010_alter_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
