# Generated by Django 5.0.3 on 2024-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0010_alter_player_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
