# Generated by Django 5.0.3 on 2024-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0012_player_nb_points_2p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='staticfiles/avatars/avatar.png', max_length=200, upload_to='staticfiles/avatars/'),
        ),
    ]
