# Generated by Django 5.0.4 on 2024-05-21 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0013_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
