# Generated by Django 5.0.3 on 2024-03-28 17:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0013_alter_player_options_player_date_joined_player_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
