# Generated by Django 5.0.6 on 2024-05-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0014_player_last_activity'),
        ('players_manager', '0014_player_nb_points_tournament'),
    ]

    operations = [
    ]
