# Generated by Django 5.0.6 on 2024-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0015_merge_20240522_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('PLAYING', 'Playing'), ('IN_TOURNAMENT', 'In Tournament')], default='OFFLINE', max_length=200),
        ),
    ]
