# Generated by Django 5.0.6 on 2024-05-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0017_alter_player_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
