# Generated by Django 5.0.6 on 2024-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0018_delete_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nb_games_2p',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_games_2p_lost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_games_2p_won',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_games_4p',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_games_4p_lost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_games_4p_won',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_points_2p',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_points_4p',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nb_points_tournament',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
    ]
