# Generated by Django 5.0.4 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0008_alter_player_avatar'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to='players_manager.player'),
        ),
    ]
