# Generated by Django 5.0.4 on 2024-04-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0008_alter_player_avatar'),
        ('tournament', '0002_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tournaments', to='players_manager.player'),
        ),
    ]
