# Generated by Django 5.0.4 on 2024-05-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='visibility',
        ),
    ]
