# Generated by Django 5.0.6 on 2024-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_rename_tournamentstats_tournamentstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentroom',
            name='owner',
        ),
        migrations.AddField(
            model_name='tournamentroom',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
