# Generated by Django 5.0.6 on 2024-05-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0013_alter_player_avatar'),
        ('tournament', '0008_remove_tournamentroom_owner_tournamentroom_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstat',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentstat',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_tournaments', to='players_manager.player'),
        ),
    ]
