# Generated by Django 5.0.6 on 2024-05-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0006_alter_twoplayersgame_id_tournament_and_more'),
        ('tournament', '0009_alter_tournamentstat_tournament_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstat',
            name='TwoPlayersGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games_manager.twoplayersgame'),
        ),
    ]
