# Generated by Django 5.0.6 on 2024-05-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournamentstat_twoplayersgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentstat',
            name='TwoPlayersGame',
        ),
    ]
