# Generated by Django 5.0.6 on 2024-05-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_remove_tournamentstat_twoplayersgame'),
        ('tournament', '0011_tournamentroom_time_created'),
    ]

    operations = [
    ]
