# Generated by Django 5.0.3 on 2024-03-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
        ('two_players_games_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('score_max', models.IntegerField(default=5)),
                ('win_player', models.CharField(max_length=200)),
                ('id_tournament', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Two_player_1', to='players_manager.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Two_player_2', to='players_manager.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Two_Players',
        ),
    ]
