# Generated by Django 5.0.3 on 2024-03-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
        ('two_players_games_manager', '0002_two_player_delete_two_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_player',
            name='win_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_player', to='players_manager.player'),
        ),
    ]
