# Generated by Django 5.0.3 on 2024-03-21 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_players_games_manager', '0003_alter_two_player_win_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='two_player',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
