# Generated by Django 5.0.3 on 2024-03-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0005_player_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='login',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
