# Generated by Django 5.0.3 on 2024-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0011_player_login_alter_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='login',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(default='x', max_length=200, unique=True),
        ),
    ]
