# Generated by Django 5.0.3 on 2024-03-28 10:54

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0012_remove_player_login_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='login',
            field=models.CharField(default='x', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
