# Generated by Django 5.0.3 on 2024-03-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0013_player_login_alter_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='login',
        ),
    ]
