# Generated by Django 5.0.3 on 2024-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nb_games_4p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_4p_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_games_4p_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/'),
        ),
    ]
