# Generated by Django 5.0.3 on 2024-03-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
        ('tournaments_manager', '0003_alter_tournament_player_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_1', to='players_manager.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_8', to='players_manager.player'),
        ),
    ]
