# Generated by Django 5.0.3 on 2024-03-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_manager', '0004_alter_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_players', models.IntegerField(choices=[(4, 'Four'), (8, 'Eight')], default=4)),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_1', to='players_manager.player')),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_2', to='players_manager.player')),
                ('player_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_3', to='players_manager.player')),
                ('player_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_4', to='players_manager.player')),
                ('player_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_5', to='players_manager.player')),
                ('player_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_6', to='players_manager.player')),
                ('player_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_7', to='players_manager.player')),
                ('player_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_player_8', to='players_manager.player')),
            ],
        ),
    ]
