# Generated by Django 5.0.6 on 2024-06-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='user_initiated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
