# Generated by Django 5.0.4 on 2024-04-23 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0001_initial'),
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='twoplayersgame',
            old_name='score_player1',
            new_name='score_user1',
        ),
        migrations.RenameField(
            model_name='twoplayersgame',
            old_name='score_player2',
            new_name='score_user2',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='player2',
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='id_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tournament', to='tournament.tournament'),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_user_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
