# Generated by Django 5.0.4 on 2024-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0003_alter_twoplayersgame_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twoplayersgame',
            name='score_max',
            field=models.IntegerField(default=3),
        ),
    ]
