# Generated by Django 5.0.4 on 2024-04-30 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0004_alter_twoplayersgame_score_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPlayersGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_user1', models.IntegerField(default=0)),
                ('score_user2', models.IntegerField(default=0)),
                ('score_user3', models.IntegerField(default=0)),
                ('score_user4', models.IntegerField(default=0)),
                ('score_max', models.IntegerField(default=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1_4', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2_4', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user3_4', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user4_4', to=settings.AUTH_USER_MODEL)),
                ('win_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_player_4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
