# Generated by Django 5.0.6 on 2024-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0006_alter_twoplayersgame_id_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoplayersgame',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
