# Generated by Django 5.0.6 on 2024-05-27 10:02

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0007_twoplayersgame_id_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='score_max',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='score_user1',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='score_user2',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='win_player',
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='users',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
