# Generated by Django 5.0.6 on 2024-05-29 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0008_remove_twoplayersgame_score_max_and_more'),
        ('players_manager', '0018_delete_friend'),
        ('tournament', '0012_merge_20240522_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='users',
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='players',
            field=models.ManyToManyField(related_name='players_temp', to='players_manager.player'),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='scores_test',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='win_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_player', to='players_manager.player'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(blank=True, null=True)),
                ('tournament_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament_level', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('players', models.ManyToManyField(related_name='players', to='players_manager.player')),
                ('tournament_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_id', to='tournament.tournamentstat')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='players_manager.player')),
            ],
        ),
    ]
