# Generated by Django 5.0.6 on 2024-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0009_remove_twoplayersgame_users_twoplayersgame_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoplayersgame',
            name='scores_test',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
