# Generated by Django 5.0.6 on 2024-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0009_remove_twoplayersgame_users_twoplayersgame_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='id_tournament',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='players',
        ),
        migrations.RemoveField(
            model_name='twoplayersgame',
            name='win_player',
        ),
        migrations.DeleteModel(
            name='FourPlayersGame',
        ),
        migrations.DeleteModel(
            name='TwoPlayersGame',
        ),
    ]
