# Generated by Django 5.0.6 on 2024-05-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_manager', '0010_twoplayersgame_scores_test'),
        ('players_manager', '0018_delete_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoplayersgame',
            name='win_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_player', to='players_manager.player'),
        ),
    ]
