# Generated by Django 5.0.3 on 2024-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_manager', '0005_tournament_title_alter_tournament_player_5_and_more'),
        ('two_players_games_manager', '0005_alter_two_player_id_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_player',
            name='id_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tournament', to='tournaments_manager.tournament'),
        ),
    ]
